### ISSUE TITLE
Seems to be hanging forever

### ISSUE THREAD

**Issue by AymericG** [gabiseabra/fontello-webpack-plugin#2]
How long does executing the plugin usually take? It's been running for more than 5 minutes and still stuck.

**Comment by gabiseabra** [comment]
That doesn't seem right, what does your webpack configuration look like? Would your mind running the tests?

`npm run test -- --timeout=6000`

**Comment by frozenfung** [comment]
stuck + 1

**Comment by frozenfung** [comment]
Just figured out what happen here! I will send a PR after verifying ;)
