### ISSUE TITLE
Bug: user options are not respected

### ISSUE THREAD

**Issue by pavelloz** [gabiseabra/fontello-webpack-plugin#8]
In my config i have:

```js
{
  fonts: ['woff', 'woff2'],
}
```

But i still get
 
```
fonticons.svg  11.1 kB          [emitted]  fonticons
fonticons.ttf  12.2 kB          [emitted]  fonticons
fonticons.woff  7.45 kB          [emitted]  fonticons
fonticons.woff2  6.35 kB          [emitted]  fonticons
```

And of course corresponding links to all those files in the .css:

```
	src: url("./fonticons.woff2") format("woff2"),
		url("./fonticons.woff") format("woff"),
		url("./fonticons.ttf") format("truetype"),
		url("./fonticons.svg") format("svg");
```

Reason: https://github.com/gabiseabra/fontello-webpack-plugin/commit/80a961301a2e611b3c8d1fe75f77efdab1554749

Usually, API of methods like `Object.assign` first takes default object and then next object will override previous one, hence, it takes options passed by the user and overrides it by defaults.

Read more: https://lodash.com/docs/4.17.4#defaultsDeep

**Comment by pavelloz** [comment]
Okay, if PR #9 is not a solution, the bug still remains.
`
  fonts: ['woff', 'woff2'],
`

is generating all the font formats.

**Comment by pavelloz** [comment]
I placed two console.logs just before merge and one after, showing final options, this is the result

```
defaults { config: undefined,
  name: 'icons',
  className: '',
  fonts: [ 'eot', 'woff2', 'woff', 'ttf', 'svg' ],
  output: { css: '[name].css', font: 'font/[name].[ext]' } }

options { config:
   { name: 'fonticon',
     css_prefix_text: 'fonticon-',
     css_use_suffix: false,
     hinting: true,
     units_per_em: 1000,
     ascent: 850,
     glyphs:
      [...] },
  fonts: [ 'woff', 'woff2' ],
  name: 'fonticons',
  output: { css: 'fonticons.css', font: '[name].[ext]' } }

this.options { config:
   { name: 'fonticon',
     css_prefix_text: 'fonticon-',
     css_use_suffix: false,
     hinting: true,
     units_per_em: 1000,
     ascent: 850,
     glyphs:
      [...] },
  name: 'icons',
  className: '',
  fonts: [ 'eot', 'woff2', 'woff', 'ttf', 'svg' ],
  output: { css: '[name].css', font: 'font/[name].[ext]' } }
```

**Comment by gabiseabra** [comment]
This should be covered by this test added a while ago https://github.com/gabiseabra/fontello-webpack-plugin/commit/ba45f0c21a67d6c07e78a40d6807037500f2c558#diff-c7aea9b827d72e09909146f074cf8ba4R31
Does the issue still persist in version 0.4.5?

**Comment by pavelloz** [comment]
0.4.5 works perfectly :)

Thank you for such a quick reaction, you are saving me a lot of GBs of transfer :)
